### ISSUE TITLE
unecessary volatile in e_reg_read

### ISSUE THREAD

**Issue by notzed** [adapteva/epiphany-sdk#10]
This:

	volatile register unsigned reg_val;

causes every use of the value to go through the stack.

relevant fragment of machine code with volatile:

  42:   0512            movfs r0,status
  44:   15dc 0400       str r0,[sp,+0x3]
  48:   15cc 0400       ldr r0,[sp,+0x3]

with volatile deleted:

  42:   0512            movfs r0,status

**Comment by olajep** [comment]
Fixed on master
https://github.com/adapteva/epiphany-libs/commit/967d4e9d31879faa57afabc661a228f318a7488d
