### ISSUE TITLE
epiphany-hal.c fails to compile

### ISSUE THREAD

**Issue by greytery** [adapteva/epiphany-sdk#12]
In function ‘e_reset_system’:
"      e_write(&dev, 0, 0, E_REG_LINK_MODE_CFG, &data, sizeof(int));"
should be:
"      e_write(&dev, 0, 0, E_REG_LINKCFG, &data, sizeof(int));"
in line with updated version of 'epiphany-hal-data.h'

(Issue raised in forum - ack'd by Andreas - but I think I should have raised a bug in the first place. tery)

**Comment by olajep** [comment]
Closing. Fixed or not applicant. There's no e-regs.h. It's named E_REG_LINKCFG in e-hal/src/epiphany-hal-data.h, and e_reset_system() doesn't use it anymore.
