### ISSUE TITLE
epiphany core sim needs external/host memory access

### ISSUE THREAD

**Issue by GravisZro** [adapteva/epiphany-sdk#47]
Unless I'm missing something, the epiphany simulator is not helpful to developers because it will segfault when trying to write to external memory that should be on it's host. e.g. 0x8e00aac0

I think this would be a apt use of the <a href="https://en.wikipedia.org/wiki/Shared_memory_(interprocess_communication)">POSIX shared memory</a> mechanism.  It may even be possible to create a linker script to build host applications without modification on a non-Parallella system that could use the shared memory.

**Comment by olajep** [comment]
Hi,

So, there are two versions of the simulator

https://github.com/adapteva/epiphany-binutils-gdb/blob/epiphany-gdb-7.6-multicore-sim/sim/epiphany/README.epiphany-elf-sim.md

**Comment by olajep** [comment]
[Ignore previous message. Accidentally pressed Ctrl+Enter]

Hi,

There are two versions of the simulator; one single-core simulator that works with the toolchain test-suite and one multicore simulator that defaults to Parallella settings (it is based on the previous one).

Both are shipped with the ESDK binaries as of 2014.11.
These binaries use the single-core simulator:
e-gdb, e-run.

And these is for the multi-core simulator:
e-mgdb, e-mrun, and e-sim.

e-sim is a frontend for e-mrun.

Here's some documentation for the multi-core version:

https://github.com/adapteva/epiphany-binutils-gdb/blob/epiphany-gdb-7.6-multicore-sim/sim/epiphany/README.epiphany-elf-sim.md

https://github.com/adapteva/epiphany-binutils-gdb/blob/epiphany-gdb-7.6-multicore-sim/sim/epiphany/README.esim.md

HTH,

Ola

**Comment by GravisZro** [comment]
I was referring to the single core simulator but it seems it will be deprecated.  It would be very helpful if there were instructions in the wiki with how to use the new sim (with examples using epiphany-examples repo).

just FYI, you can edit your comments on github if you were unaware.
