### ISSUE TITLE
simulator build fails with multiple defined symbols on Fedora 22 for 2015.1

### ISSUE THREAD

**Issue by martyfouts** [adapteva/epiphany-sdk#56]
I attempt to build 2015.1 according to the instructions:

  git clone https://github.com/adapteva/epiphany-sdk sdk
  export EPIPHANY_BUILD_HOME=`pwd`
  sdk/download-toolchain.sh
  /sdk/build-epiphany-sdk.sh -C -R -a x86_64

The build fails.  The log shows that the build failure is in building run, and that many symbols in run are duplicates.  Example fragments from the log:

/home/marty/projects/adapteva/libtool: compile:  gcc -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DTIME_WITH_SYS_TIME=1 -DHAVE_LOCALE_H=1 -DHAVE_WCHAR_H=1 -DHAVE_STDARG=1 -DHAVE_SYS_TIME_H=1 -DHAVE_STDINT_H=1 -DHAVE_VA_COPY=1 -DHAVE_SETLOCALE=1 -DHAVE_GETTIMEOFDAY=1 -DHAVE_HOST_CORE2=1 -DHAVE_LONG_LONG=1 -DHAVE_INTMAX_T=1 -DMPFR_HAVE_FESETROUND=1 -DHAVE_DENORMS=1 -DHAVE_ROUND=1 -DHAVE_TRUNC=1 -DHAVE_FLOOR=1 -DHAVE_CEIL=1 -DHAVE_NEARBYINT=1 -DHAVE_LDOUBLE_IEEE_EXT_LITTLE=1 -DLT_OBJDIR=\".libs/\" -DHAVE_ATTRIBUTE_MODE=1 -DHAVE_ALLOCA_H=1 -I. -I/home/marty/projects/adapteva/2015.1/unisrc-2015.1/mpfr -I/home/marty/projects/adapteva/2015.1/builds/bd-x86_64-2015.1/./gmp -g -O2 -MT exceptions.lo -MD -MP -MF .deps/exceptions.Tpo -c /home/marty/projects/adapteva/2015.1/unisrc-2015.1/mpfr/exceptions.c -o exceptions.o
2015.1/unisrc-2015.1/sim/epiphany/../common/cgen-ops.h:331: multiple definition of `SUBWORDSIUQI'
libsim.a(cgen-utils.o):/home/marty/projects/adapteva/2015.1/unisrc-2015.1/sim/epiphany/../common/cgen-ops.h:331: first defined here
libsim.a(epiphany.o): In function `SUBWORDDIQI':
/home/marty/projects/adapteva/2015.1/unisrc-2015.1/sim/epiphany/../common/cgen-ops.h:338: multiple definition of `SUBWORDDIQI'
libsim.a(cgen-utils.o):/home/marty/projects/adapteva/2015.1/unisrc-2015.1/sim/epiphany/../common/cgen-ops.h:338: first defined here

...

Makefile:12507: recipe for target 'all-sim' failed
make: *** [all-sim] Error 2

**Comment by martyfouts** [comment]
forgot to specify the gcc version:

$ gcc --version
gcc (GCC) 5.1.1 20150618 (Red Hat 5.1.1-4)

**Comment by martyfouts** [comment]
I think I see the problem.  Here's an example.  (All paths relative to unisrc-2015.1/sim)

The code is using a technique to inline functions if certain variables are defined.  common/sim-arange.h shows this with

#ifdef HAVE_INLINE
#ifdef SIM_ARANGE_C
#define SIM_ARANGE_INLINE INLINE
#else
#define SIM_ARANGE_INLINE EXTERN_INLINE
#endif
#include "sim-arange.c"
#else
#define SIM_ARANGE_INLINE
#endif
#define SIM_ARANGE_C_INCLUDED

It appears that the problem with this approach is that it's possible for GCC to decide not to inline a function.  If this happens, then that function is copied int every C file that includes sim-basics.h leading to it being compiled everywhere but not inlined, resulting in multiple symbol definitions that are discovered by ld, breaking the build.

I don't know what the solution is.

**Comment by martyfouts** [comment]
My analysis was in error.  The problem is that the meaning of 'extern inline' is different in gnu89 than it is in gnu11 and gcc 5 defaults to gnu11

https://gcc.gnu.org/gcc-5/porting_to.html  describes the situation.

The solution appears to be to change the definition of FOO_INLINE to EXTERN_INLINE in foo.h and to compile with -std=gnu89

**Comment by Shadowigor** [comment]
I have the same problem with gcc 5.2.0. Any solutions yet?

**Comment by olajep** [comment]
@Shadowigor 
Can you please try again. Should be fixed in:
https://github.com/adapteva/epiphany-sdk/commit/8335158dba213946ac7c1ae7f95cb434eedd0cad

You need to cd into sdk and do a git pull to get the fix

// Ola

**Comment by Shadowigor** [comment]
Thank you! It works now.

**Comment by olajep** [comment]
closing as it seems fixed.
