### ISSUE TITLE
pull requests failing when cloning gnu tools

### ISSUE THREAD

**Issue by martyfouts** [adapteva/epiphany-sdk#57]
Attempting to obtain gcc (and other tools) via git fails on Fedora 22 using git 2.4.3:

to reproduce:

$  git clone https://github.com/adapteva/epiphany-sdk sdk
$ ./sdk/build-epiphany-sdk.sh -C -R -a x86_64

from the log file

Fetching gcc
fatal: No remote repository specified.  Please, specify either a URL or a
remote name from which new revisions should be fetched.
ERROR (versions): Failed to fetch gcc

similarly for binutils, console output:

Fetching binutils
Checking out epiphany-binutils-esdk-2015.1
Pulling latest version of epiphany-binutils-esdk-2015.1
ERROR (versions): Failed to pull epiphany-binutils-esdk-2015.1 of binutils

this repeats for all of the cloned directories.  It appears that some of the logic around checking out or pulling the correct revision is failing, reporting that the right version couldn't be checked out or pulled, when it had been.

If the cloning is done manually, the same problem crops up later when fetching the epiphany library and parallella-linux repositories

**Comment by martyfouts** [comment]
This failure is because the check for detached head fails to match git 2.4.3's idea of a detached head.

The test is 

if git branch | grep -q -e '\* (detached from .*)' -e '\* (no branch)'

but 2.4.3's branch output is

$ git branch
* (HEAD detached at epiphany-gcc-esdk-2015.1)
  epiphany-gcc-4.8-software-cache

the addition of "HEAD " between the '(' and "detached" breaks the intended match as does the change from 'from' to 'at'

the solution to this problem is to add a regexp to account for the possibility of HEAD being present.

Here's a patch that does this:

$ git diff
diff --git a/get-versions.sh b/get-versions.sh
index cf7dc1c..0ececf3 100755
--- a/get-versions.sh
+++ b/get-versions.sh
@@ -206,7 +206,7 @@ do
        logterm "Fetching ${tool}"

        # See note below why two expressions are requied.
-       if git branch | grep -q -e '\* (detached from .*)' -e '\* (no branch)'
+       if git branch | grep -q -e '\* (detached from .*)' -e '\* (no branch)' -e '\* (HEAD detached at .*)'
        then
            # Try to guess a good branch with a working tree similar to the
            # tag's
@@ -216,7 +216,7 @@ do
            fi

            # Check if repo is still in detached head
-           if git branch | grep -q -e '\* (detached from .*)' -e '\* (no branch)'
+           if git branch | grep -q -e '\* (detached from .*)' -e '\* (no branch)' -e '\* (HEAD detached at .*)'
            then
                # Detached head. Checkout an 'arbitrary' branch...
                # ... but it cannot be a remote name, or HEAD etc. ...
@@ -267,7 +267,7 @@ do
         # If tree is in detahed state, output differs between Git versions:
         # Git 1.8 prints: * (detached from <tag_name>>)
         # Git <1.8 prints: * (no branch)
-        if ! git branch | grep -q -e '\* (detached from .*)' -e '\* (no branch)'
+        if ! git branch | grep -q -e '\* (detached from .*)' -e '\* (no branch)' -e '\* (HEAD detached at .*)'
         then
             logterm "Pulling latest version of ${branch}"
             if ! git pull >> ${logfile} 2>&1

**Comment by befedo** [comment]
Hi martyfouts,
I also got this failure while my git version is 2.6.1-1. Could you please describe where to apply this patch and provide an clean 'output' from the git diff, this one above is not really readable on the git hub web page.

Thanks for your time and best regards,

Befedo

**Comment by olajep** [comment]
This got lost in my inbox, sorry.
Patch applied against master, 2015.1, and 2014.11

**Comment by olajep** [comment]
closing. should be fixed. tested with git 2.6.1. feel free to reopen if it still doesn't work for you.
