### ISSUE TITLE
Multicore Epiphany simulator fails to build Fedora 22 / gcc (3.4 or 5.1.1)

### ISSUE THREAD

**Issue by martyfouts** [adapteva/epiphany-sdk#58]
To reproduce:

$ ./sdk/build-epiphany-sdk.sh -C -R -a x86_64

< BIG SNIP >

Building Epiphany multicore simulator...
Error: Epiphany multicore simulator build failed.
Build failed. See /home/marty/projects/adapteva/2015.1/logs/2015.1/build-2015-07-28-2052.log for details.
The toolchain build failed!

--------

Here's a fragment from the log:

sim/epiphany/../../opcodes  -pthread -lrt -fPIC -fvisibility=hidden  -c -o nrun.o -MT nrun.o -MMD -MP -MF .deps/nrun.Tpo /home/marty/projects/adapteva/2015.1/gdb-multicore-sim/sim/epiphany/../common/nrun.c
In file included from /home/marty/projects/adapteva/2015.1/gdb-multicore-sim/sim/epiphany/esim/esim.c:53:
/home/marty/projects/adapteva/2015.1/gdb-multicore-sim/sim/epiphany/esim/esim-int.h: In function `es_cas8':
/home/marty/projects/adapteva/2015.1/gdb-multicore-sim/sim/epiphany/esim/esim-int.h:61: warning: implicit declaration of function `__sync_val_compare_and_swap'
/home/marty/projects/adapteva/2015.1/gdb-multicore-sim/sim/epiphany/esim/esim-int.h: In function `es_atomic_incr8':
/home/marty/projects/adapteva/2015.1/gdb-multicore-sim/sim/epiphany/esim/esim-int.h:74: warning: implicit declaration of function `__sync_fetch_and_add'
/home/marty/projects/adapteva/2015.1/gdb-multicore-sim/sim/epiphany/esim/esim-int.h: At top level:
/home/marty/projects/adapteva/2015.1/gdb-multicore-sim/sim/epiphany/esim/esim-int.h:114: error: redefinition of typedef 'sim_cpu'
/home/marty/projects/adapteva/2015.1/gdb-multicore-sim/sim/epiphany/../common/sim-base.h:79: error: previous declaration of 'sim_cpu' was here
/home/marty/projects/adapteva/2015.1/gdb-multicore-sim/sim/epiphany/esim/esim-int.h:175: error: redefinition of typedef 'es_state'
/home/marty/projects/adapteva/2015.1/gdb-multicore-sim/sim/epiphany/esim/esim.h:57: error: previous declaration of 'es_state' was here
/home/marty/projects/adapteva/2015.1/gdb-multicore-sim/sim/epiphany/esim/esim.h:77: warning: 'es_initialized' declared inline after being called
/home/marty/projects/adapteva/2015.1/gdb-multicore-sim/sim/epiphany/esim/esim.h:77: warning: previous declaration of 'es_initialized' was here
Makefile:579: recipe for target 'esim/esim.o' failed

-----------------------------------------------------

**Comment by martyfouts** [comment]
There are 3 bugs here, two of which are similar.  C doesn't actually allow  'typedef struct _foo foo;' in one header and 'typedef struct _foo { ... } foo;' in a different one, if the two headers are both included by the same C file.  The solution, for es_state and sim_cpu, is to replace the first header with a simple 'struct _foo' in the first header and fix all the places where foo is used to struct _foo.

The third problem shows up when the first two are fixed:
`__sync_fetch_and_add'
`__sync_fetch_and_and'
`__sync_fetch_and_or'
`__sync_val_compare_and_swap'

are all referenced but none of them are defined.  I don't have a solution for this problem.

**Comment by martyfouts** [comment]
Ooops.  The 3rd issue is because I'm using GCC 3.4 which doesn't support the sync functions.  I guess it's time to fix the problem with 'extern inline'

**Comment by olajep** [comment]
closing, works for me. You probably need at least GCC 4.8.
