### ISSUE TITLE
the p[i] operand miss calculates the struct size 

### ISSUE THREAD

**Issue by oz-shmueli** [adapteva/epiphany-sdk#59]
typedef struct {
int x ;
int y;
.
.
.
} e_t;
e_t p[N];
host code copies the struct from epiphany and prints it  
looks like  p[1].x=1; will cause p[1].y to be 1
i'm thinking alignment/ packing  differences from host compiler to epiphany compiler

**Comment by olajep** [comment]
try __attribute__((packed))

```c
typedef struct {
int x ;
int y;
.
.
.
} __attribute__((packed)) e_t ;
e_t p[N];
```

**Comment by olajep** [comment]
closing, this is not a bug. when you share a struct between archs you need to be explicit w/ the layout.

attribute packed and attribute aligned are your friends here.

// Ola
