### ISSUE TITLE
ESYS mmap failure.

### ISSUE THREAD

**Issue by baryluk** [adapteva/epiphany-sdk#62]
Hi,

I removed /opt/adapteva, and have built esdk from latest and greatest (2015.1, native build), and have updated all the paths. Most of the examples are working (from root), but I do get some error messages:

root@linaro-nano:/home/linaro/epiphany-examples/apps/hello-world# ./build.sh && ./run.sh 
hello_world.elf: ee_write_esys(): ESYS mmap failure.
hello_world.elf: e_reset_system(): Failed

  0: Message from eCore 0x8ca ( 3, 2): "Hello World from core 0x8ca!"
  1: Message from eCore 0x84b ( 1, 3): "Hello World from core 0x84b!"
  2: Message from eCore 0x84b ( 1, 3): "Hello World from core 0x84b!"
  3: Message from eCore 0x888 ( 2, 0): "Hello World from core 0x888!"
  4: Message from eCore 0x849 ( 1, 1): "Hello World from core 0x849!"
  5: Message from eCore 0x88b ( 2, 3): "Hello World from core 0x88b!"
  6: Message from eCore 0x88b ( 2, 3): "Hello World from core 0x88b!"
  7: Message from eCore 0x8ca ( 3, 2): "Hello World from core 0x8ca!"
  8: Message from eCore 0x80a ( 0, 2): "Hello World from core 0x80a!"
  9: Message from eCore 0x808 ( 0, 0): "Hello World from core 0x808!"
 10: Message from eCore 0x8c8 ( 3, 0): "Hello World from core 0x8c8!"
 11: Message from eCore 0x8c9 ( 3, 1): "Hello World from core 0x8c9!"
 12: Message from eCore 0x88a ( 2, 2): "Hello World from core 0x88a!"
 13: Message from eCore 0x88b ( 2, 3): "Hello World from core 0x88b!"
 14: Message from eCore 0x8cb ( 3, 3): "Hello World from core 0x8cb!"
 15: Message from eCore 0x84a ( 1, 2): "Hello World from core 0x84a!"
 16: Message from eCore 0x88a ( 2, 2): "Hello World from core 0x88a!"
 17: Message from eCore 0x84b ( 1, 3): "Hello World from core 0x84b!"
 18: Message from eCore 0x848 ( 1, 0): "Hello World from core 0x848!"
 19: Message from eCore 0x8ca ( 3, 2): "Hello World from core 0x8ca!"
hello_world.elf: ee_read_esys(): ESYS mmap failure.
hello_world.elf: ee_read_esys(): ESYS mmap failure.
hello_world.elf: ee_read_esys(): ESYS mmap failure.
hello_world.elf: ee_write_esys(): ESYS mmap failure.
hello_world.elf: ee_write_esys(): ESYS mmap failure.
hello_world.elf: ee_write_esys(): ESYS mmap failure.
$

Some other examples works (eprime), but some dont (fft2d, matmul-16 - they are stuck and do nothing).

All with these messages:

root@linaro-nano:/home/linaro/epiphany-examples/apps/matmul-16# ./run.sh 
------------------------------------------------------------
Calculating:   C[512][512] = A[512][512] * B[512][512]
matmul.elf: ee_write_esys(): ESYS mmap failure.
matmul.elf: e_reset_system(): Failed

stuck for minutes

^C

**Comment by olajep** [comment]
Hi,

You need a more up to date kernel / bitstream combo.
The easiest way to get that is to download a image for the most recent release.

ftp://ftp.parallella.org/ubuntu/dists/trusty/image/
ubuntu-14.04-headless-z7010-20150130.1.img.gz
or
ubuntu-14.04-headless-z7020-20150130.1.img.gz


// Ola

**Comment by olajep** [comment]
closing, not applicable
