### ISSUE TITLE
unable to build ESDK 2016.3.1 for x86_64 (distro: Fedora Core 23)

### ISSUE THREAD

**Issue by DonQuichotteComputers** [adapteva/epiphany-sdk#64]
Was though OK with ESDK 2015.1 for x86_64.
Explained on
https://parallella.org/forums/viewtopic.php?f=48&t=3682&p=17704#p17704

**Comment by olajep** [comment]
You need to have guile1.8 installed

This should work on Fedora
```sh
sudo yum install compat-guile18
```

**Comment by DonQuichotteComputers** [comment]
:D it works, many thanks Ola :+1:
