### ISSUE TITLE
gdb: Build with expat support

### ISSUE THREAD

**Issue by olajep** [adapteva/epiphany-sdk#65]
Needed for extended remote debug protocol.

**Comment by jeremybennett** [comment]
Specifically needed for things like remote target description or memory maps, which are described n XML. Not necessarily just extended remote working.

**Comment by olajep** [comment]
Fixed here:

https://github.com/adapteva/epiphany-sdk/commit/8cbe2e9ad98741f0ef4ea0ddf0a00d1d677e3b17
