### ISSUE TITLE
e-as doesn't recognize some system registers

### ISSUE THREAD

**Issue by alexrp** [adapteva/epiphany-sdk#8]
- The `debugstatus` register is not understood. Presumably, what `epiphany.cpu` calls `debug` is equivalent to what the manual calls `debugstatus`.
- The `fstatus` register is not understood. Probably what `epiphany.cpu` calls `hstatus`.
- The `multicast` register is not understood. Probably what `epiphany.cpu` calls `meshmulticast`.
- The `debugcmd` and `resetcore` registers are not understood.
- The `cmeshroute`, `xmeshroute`, and `rmeshroute` registers are not understood.

**Comment by olajep** [comment]
### Ok:
* debugstatus 
* debugcmd


### Renamed

`multicast` is named `meshmulticast`. I think we should change it in the reference manual and not in the code.

### Missing:
* cmeshroute
* xmeshroute
* rmeshroute
